### ISSUE TITLE
Headers are not deleted when have a blank value, even though they should

### ISSUE THREAD

**Issue by darkpixel93** [charonn0/RB-libcURL#15]
So according to Daniel Stenberg, the way to remove a header is to pass a blank value with the name of the header as you can see here: http://stackoverflow.com/a/26250768

I followed his steps with:

```realbasic
Dim h as new InternetHeaders
h.AppendHeader("X-Requested-With","")
c.SetRequestHeaders(h)
```

SetRequestHeaders formats it the way it should be ("X-Requested-With:"), but the header doesn't get deleted. Instead it is added multiple times.
I "remove" a header each time I add one, so not sure why it does not work.

Screenshot from Fiddler: http://i.imgur.com/f6OkS0O.png

Let me know if you need a sample project.

**Comment by charonn0** [comment]
This problem was fixed in commit 9e258b499631f6417555c1ebaa20757291e15455, which replaced the SetRequestHeader**s** function with one called [SetRequestHeader](https://github.com/charonn0/RB-libcURL/wiki/cURLManager.SetRequestHeader).

**Comment by charonn0** [comment]
A workaround would be to delete all previously set headers by passing Nil:

```vbnet
  c.SetRequestHeaders(Nil)
```

**Comment by darkpixel93** [comment]
Thank you, I will try that
