### ISSUE TITLE
64-bit not supported

### ISSUE THREAD

**Issue by charonn0** [charonn0/RB-libcURL#21]
This project has not yet undergone any sort of testing for 64-bit compatibility.

**Comment by trippleflux** [comment]
Any news on 64 bit supports?, especially on windows, after building the 64 bit executable, it giving out an error when launched the demo
![libcurl](https://user-images.githubusercontent.com/1216215/29973504-f8a34448-8f59-11e7-9b74-025d4ca0f757.png)

**Comment by charonn0** [comment]
No news at this time. Once Xojo enables 64 bit debugging on Windows I'll be able to start the work,

**Comment by charonn0** [comment]
I'm officially closing this issue since x64 is now working in all my tests. If you encounter a bug relating to x64 please open a new issue.
