### ISSUE TITLE
Doesn't find libcurl.dll

### ISSUE THREAD

**Issue by ThuGie** [charonn0/RB-libcURL#31]
### Expected behavior
Finding liburl.dll
### Actual behavior
It still complains it doesnt find it tried different versions of the dll
### Steps to reproduce the behavior
just open in debug of a build version.

If i need more or a specific version could you provide direct links to them ?

**Comment by charonn0** [comment]
libcurl.dll typically requires several additional DLLs depending on what options were enabled/disabled when the DLL itself was compiled. If a feature is enabled the the associated DLL(s) must be present in the same folder as the main libcurl.dll file. If any of the expected DLLs are not present then loading libcurl.dll will fail.  

Also, remember that 32-bit apps require 32-bit DLLs , and 64-bit apps require 64-bit DLLs . 

I usually recommend using the official builds from the curl project website. [The download page](https://curl.se/windows/) provides links to all the different dependencies needed for the version being downloaded. Download the main DLL and then also download each dependency package. From each package copy all DLL files into the same directory as the main libcurl.dll file. 

Your DLL folder should look something like this:
![libcurldlls](https://user-images.githubusercontent.com/585485/116328290-8cce1a00-a77d-11eb-8367-cd58fb5d5deb.png)
