### ISSUE TITLE
cannot GET data from one specific URL

### ISSUE THREAD

**Issue by VanDerLars** [charonn0/RB-libcURL#32]
Hi,

libcURL works like a charm, but only on one specific URL, we run into a #22 HTTP error.

Our method:

``` VB
Var curl As New cURLClient
curl.EasyItem.TimeOut = 3

var ascURL as string = "https://graphhopper.com/api/1/"

Var theResult As String
If Not curl.Get(ascURL) Then
  via.Log.toConsole("CURL ERROR  Position 2: #" + curl.LastError.ToString + " -> https://curl.se/libcurl/c/libcurl-errors.html")
  via.Log.toConsole("URL: " + ascURL)
  
Else
  theResult = curl.GetDownloadedData
  VIA.Log.toConsole("result received: " + theResult.Length.ToString + "chars long")
  VIA.Log.toConsole("http call: successfull")
  
  Return theResult
End If
```

We always end in the error-section with a #22 cURL error (curl.LastError.ToString).
The page it self is reachable, also when we use cURL on the commandline. Also other calls over the same method (with different URLs) are working as expected.

What is the issue here? What do we miss?

Thanks!!!

**Comment by charonn0** [comment]
curl error 22 means that the server returned an error code (such as `404 not found`). The cURLClient class by default will fail the whole transfer if the server sends such an error response. 

To treat server errors as successful transfers set `FailOnServerError=False`:

```xojo
  Var curl As New cURLClient
  curl.EasyItem.FailOnServerError = False
```

When I test `https://graphhopper.com/api/1/` I receive the same `400 bad request` response in libcurl, curl command line, and in a web browser. The downloaded data is a JSON message: 

```json
{"message":"No parameters specified, at least 'key' is necessary. Please register and see documentation: https://www.graphhopper.com/developers/"}
```

**Comment by VanDerLars** [comment]
Okay, so the request returns false due to the http status code, but we can still access the data there. Then this was just a misunderstanding of the implementation.

Thank you very much!
