### ISSUE TITLE
PUT to SMB generates 0 byte files

### ISSUE THREAD

**Issue by nickheaphy** [charonn0/RB-libcURL#35]
### Expected behavior

The file is transferred to the SMB server

### Actual behavior

A zero byte file is created on the SMB server

### Steps to reproduce the behavior

While I encounter the problem in my project, I also can't get a PUT working in the cURL.rbvcp sample project. The below steps are using the sample project.

If I enter the path as `smb://192.168.1.10/delete-me/file.pdf` and then in the Raw Options enter my username and password, then PUT a pdf file (using either 'Put' or 'Put Threaded') nothing much seems to happen. I do end up with a zero byte file in the SMB share with the name `file.pdf` but no data is transferred.

The Xojo debug messages says "Text: Connected to 192.168.1.10 (192.168.1.10) port 445 (#0)"

If I use `curl -T file.pdf -u username:password smb://192.168.1.10/delete-me/` then this does transfer the file correctly, so the SMB should be working.

In my application I do get more error messages from libcurl in the debug console - it gives me a "Text: Send failure: Broken pipe" and I also get a zero byte file on the SMB server.

I have tried this on both OSX (libcurl 7.79.1) and on Windows 11 (libcurl 7.83.1) and neither work with SMB.

If using a WebDAV destination rather than SMB everything works as expected.

Any ideas?

**Comment by charonn0** [comment]
It sounds like you're using the demo window. What happens if you use the cURLClient class directly?

```xojo
 // in App.Open
  Dim file As FolderItem = SpecialFolder.Desktop.Child("file.pdf")
  Dim upload As BinaryStream = BinaryStream.Open(file)
  Dim curl As New cURLClient
  curl.Username = "username"
  curl.Password = "password"
  
  If curl.Put("smb://192.168.1.10/delete-me/file.pdf", upload) Then
    MsgBox("Success")
  Else
    MsgBox("Error: " + libcURL.FormatError(curl.LastError))
  End If
  upload.Close()
```

My suspicion is that the problem lies in the demo window rather than in the project proper.

**Comment by nickheaphy** [comment]
Funnily enough, I just sat down to write a minimal example like you posted as I wondered something similar.

With your above code I run into the same problem. I never get either of the Success or Error MsgBox popups. The main thread hangs. The debug messages shows the "Connected to 192.168.1.10 (192.168.1.10) port 445 (#0)" but then nothing.

If I break out into the debugger it is always in the cURLSession.Perform function. Stepping through it seems like the MultiHandle.PerformOnce function just keeps looping (but to be honest I don't understand exactly what is happening, your code is way above my head!)

Again, if I change to a WebDav URL, everything works as expected.

**Comment by charonn0** [comment]
There is a known bug (https://github.com/curl/curl/issues/7896) in curl where SMB uploads from stdin generate an empty file and then hang. It's not quite the same (we're not using stdin), but otherwise it seems to match. One of the comments suggests that specifying the upload size in advance might help:

```xojo 
Call curl.SetOption(libcURL.Opts.INFILESIZE, file.Length) ' use INFILESIZE_LARGE for files >2GB
```

It might also be enlightening to see the debug output from a successful command line upload. Add `-v` to the command line for verbose mode.

**Comment by nickheaphy** [comment]
Spending a bit more time trying to understand what is happening... for some reason the code keeps entering `EasyHandle.curlRead` even though the `UploadStream.Read(sz)` returns 0 bytes because it is at the end of the file.

Not much info in the verbose output.
```
nick.h@Nicks-MBP Desktop % curl -v -T file.pdf -u user:password smb://192.168.1.10/delete-me/file.pdf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.168.1.10:445...
* Connected to 192.168.1.10 (192.168.1.10) port 445 (#0)
100 25024    0     0  100 25024      0   374k --:--:-- --:--:-- --:--:--  444k
* Connection #0 to host 192.168.1.10 left intact
```

I will try adding the file size and see if that helps.

**Comment by nickheaphy** [comment]
Genius!

Adding `Call curl.SetOption(libcURL.Opts.INFILESIZE, file.Length)` before `curl.Put` gives a successful upload!

**Comment by nickheaphy** [comment]
Hmmmm, now I just need to work out how I implement that in my code with the custom Readable class that I have written that does not know the size of the data... nuts 🤣

**Comment by charonn0** [comment]
According to the libcurl documentation:

> This option (INFILESIZE) does not limit how much data libcurl will actually send, as that is controlled entirely by what the read callback returns, but telling one value and sending a different amount may lead to errors. 

So maybe if you specify a ridiculously large size in advance? It might generate an error, but I wonder if the file will be uploaded anyway.

**Comment by nickheaphy** [comment]
Thanks. I had the same thought but when I tried it was back to hanging, stuck in the same `cURLSession.Perform` loop.

I am working on my code with some known file lengths to make sure that setting the filesize works in conjunction with the custom Readable class, then I will have a think about the best way to deal with the unknown (maybe just telling the users they have to use WebDAV 😜)

**Comment by charonn0** [comment]
Calling `cURLClient.Abort()`  should break the loop and cause an error. This will require some juggling since the code that waits for the EOF has to run concurrently with the code that's performing the transfer. Which means either using asynchronous transfers to run both on the event loop/main thread, or using two separate threads.

```xojo
curl.Put("smb://192.168.1.10/delete-me/file.pdf", upload) ' async Put()
Do Until upload.EOF
  App.DoEvents()   // do not do this in real code. Use a Timer to detect the EOF
Loop
curl.Abort()
upload.Close()
```

**Comment by nickheaphy** [comment]
That's a good idea.

I think I also have a strategy for figuring out my Reader.Length which in my limited testing seems to be working and the file transfer seems to be matching when comparing checksums. Next week I will try with more than just simulated data.

Thanks for all your help.
